# This is a basic workflow to help you get started with Actions

name: Algolia-Product-Sync-Everyday

on:
  schedule:
    - cron: "0   18  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call algoliaProductSync api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/algoliaProductSync' \
