# This is a basic workflow to help you get started with Actions

name: Algolia-Delete-Everyday

on:
  schedule:
    - cron: "0   19  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call deleteAlgolia api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/deleteAlgolia' \
