# This is a basic workflow to help you get started with Actions

name: Category-Path-Everyday

on:
  schedule:
    - cron: "30   15  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call categoryPath api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/categoryPath' \
