# This is a basic workflow to help you get started with Actions

name: Category-Count-Everyday

on:
  schedule:
    - cron: "0   15  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call categoryCount api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/categoryCount' \
