name: Data-Completeness-Everyday

on:
  schedule:
    - cron: "0   17  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call dataCompleteness api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/dataCompleteness' \
