name: Scrape-Everyday

on:
  schedule:
    - cron: "0   14  *   *   *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call scrape api route
        run: |
          curl --request POST \
          --url 'https://www.appcity.com/api/scrape' \
